server:
  port: 8081
#  port: 8081
#  8081 nginx反向代理此端口. 配置文件在nginx.conf中 .
# nginx 自己向外开放8080端口给client访问
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://<your-ip>/rr?useSSL=false&serverTimezone=UTC
    username: <>
    password: <>
  redis:
    host: <>
    port: <>
    password: <>
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.explorer.entity # 别名扫描包
logging:
  level:
    com.explorer: debug
  pattern:
    dateformat: mm:ss.SSS
#    redisson
RedisSingleServerConfig:
  address: <>
  password: <>
